# Generated by Django 4.1.3 on 2022-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
